version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: readsy_postgres
    restart: always
    environment:
      POSTGRES_USER: readsy
      POSTGRES_PASSWORD: readsy
      POSTGRES_DB: readsy_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: readsy_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  adminer:
    image: adminer
    container_name: readsy_adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
volumes:
  pgdata:
  redisdata: 